language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.3

before_script:
  - composer selfupdate
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml