language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer selfupdate
  - composer install

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
